from flask import Flask, render_template
import random

app = Flask(__name__)

# Sample data for cards
cards = [
    {"name": "The Fool", "frontImage": "static/images/the_fool.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Magician", "frontImage": "static/images/the_magician.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The High Priestess", "frontImage": "static/images/the_high_priestess.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Empress", "frontImage": "static/images/the_empress.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Emperor", "frontImage": "static/images/the_emperor.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Hierophant", "frontImage": "static/images/the_hierophant.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Lovers", "frontImage": "static/images/the_lovers.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Chariot", "frontImage": "static/images/the_chariot.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Strength", "frontImage": "static/images/strength.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Hermit", "frontImage": "static/images/the_hermit.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Wheel of Fortune", "frontImage": "static/images/wheel_of_fortune.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Justice", "frontImage": "static/images/justice.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Hanged Man", "frontImage": "static/images/the_hanged_man.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Death", "frontImage": "static/images/death.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Temperance", "frontImage": "static/images/temperance.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Devil", "frontImage": "static/images/the_devil.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Tower", "frontImage": "static/images/the_tower.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Star", "frontImage": "static/images/the_star.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Moon", "frontImage": "static/images/the_moon.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The Sun", "frontImage": "static/images/the_sun.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Judgement", "frontImage": "static/images/judgement.jpg", "backImage": "static/images/back.jpg"},
    {"name": "The World", "frontImage": "static/images/the_world.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ace of Wands", "frontImage": "static/images/ace_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Two of Wands", "frontImage": "static/images/two_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Three of Wands", "frontImage": "static/images/three_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Four of Wands", "frontImage": "static/images/four_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Five of Wands", "frontImage": "static/images/five_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Six of Wands", "frontImage": "static/images/six_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Seven of Wands", "frontImage": "static/images/seven_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Eight of Wands", "frontImage": "static/images/eight_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Nine of Wands", "frontImage": "static/images/nine_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ten of Wands", "frontImage": "static/images/ten_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Page of Wands", "frontImage": "static/images/page_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Knight of Wands", "frontImage": "static/images/knight_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Queen of Wands", "frontImage": "static/images/queen_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "King of Wands", "frontImage": "static/images/king_of_wands.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ace of Cups", "frontImage": "static/images/ace_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Two of Cups", "frontImage": "static/images/two_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Three of Cups", "frontImage": "static/images/three_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Four of Cups", "frontImage": "static/images/four_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Five of Cups", "frontImage": "static/images/five_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Six of Cups", "frontImage": "static/images/six_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Seven of Cups", "frontImage": "static/images/seven_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Eight of Cups", "frontImage": "static/images/eight_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Nine of Cups", "frontImage": "static/images/nine_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ten of Cups", "frontImage": "static/images/ten_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Page of Cups", "frontImage": "static/images/page_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Knight of Cups", "frontImage": "static/images/knight_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Queen of Cups", "frontImage": "static/images/queen_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "King of Cups", "frontImage": "static/images/king_of_cups.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ace of Swords", "frontImage": "static/images/ace_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Two of Swords", "frontImage": "static/images/two_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Three of Swords", "frontImage": "static/images/three_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Four of Swords", "frontImage": "static/images/four_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Five of Swords", "frontImage": "static/images/five_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Six of Swords", "frontImage": "static/images/six_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Seven of Swords", "frontImage": "static/images/seven_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Eight of Swords", "frontImage": "static/images/eight_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Nine of Swords", "frontImage": "static/images/nine_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ten of Swords", "frontImage": "static/images/ten_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Page of Swords", "frontImage": "static/images/page_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Knight of Swords", "frontImage": "static/images/knight_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Queen of Swords", "frontImage": "static/images/queen_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "King of Swords", "frontImage": "static/images/king_of_swords.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ace of Pentacles", "frontImage": "static/images/ace_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Two of Pentacles", "frontImage": "static/images/two_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Three of Pentacles", "frontImage": "static/images/three_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Four of Pentacles", "frontImage": "static/images/four_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Five of Pentacles", "frontImage": "static/images/five_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Six of Pentacles", "frontImage": "static/images/six_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Seven of Pentacles", "frontImage": "static/images/seven_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Eight of Pentacles", "frontImage": "static/images/eight_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Nine of Pentacles", "frontImage": "static/images/nine_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Ten of Pentacles", "frontImage": "static/images/ten_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Page of Pentacles", "frontImage": "static/images/page_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Knight of Pentacles", "frontImage": "static/images/knight_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "Queen of Pentacles", "frontImage": "static/images/queen_of_pentacles.jpg", "backImage": "static/images/back.jpg"},
    {"name": "King of Pentacles", "frontImage": "static/images/king_of_pentacles.jpg", "backImage": "static/images/back.jpg"}
 # Add more cards here up to 78 cards
]

@app.route('/')
def index():
    random.shuffle(cards)  # Shuffle the cards list
    return render_template('index.html', cards=cards)

if __name__ == '__main__':
    app.run(debug=True)
